### ISSUE TITLE
Npm install problem

### ISSUE THREAD

**Issue by Gasteclair** [reswitched/pegaswitch#31] opened 2017-06-17 20:47 UTC
Error during npm install : 
![image](https://user-images.githubusercontent.com/21268663/27256215-aa5e23fc-53ae-11e7-916f-219167163ab2.png)
I try everything, I installed python, other versions of node, removed cache, run as administrator.
But it doesn't work

**Comment by Fruitboompje** [comment] 2017-06-20 20:18
@Gasteclair I suggest you try using
`npm install --global --production windows-build-tools`
Let me know!

**Comment by Lusameme** [comment] 2017-08-08 22:20
@Fruitboompje had the same issue installed fine but then got this error when i tried to start up
![error](https://user-images.githubusercontent.com/22406854/29097120-ff6e329e-7c4c-11e7-966f-4ccac4b5e74b.png)

**Comment by Haaroon** [comment] 2017-09-23 12:48
Current build ran fine on npm 7.10.0 on OSX.

**Comment by Jhynjhiruu** [comment] 2017-10-02 19:10
![image](https://user-images.githubusercontent.com/24824597/31094614-b9ce14ca-a7ad-11e7-9f0c-d49617558dba.png)
I get this error, even after ```npm install --global --production windows-build-tools```

**Comment by JoelLarson** [comment] 2017-10-04 03:58
@Jhynjhiruu 

```
Error: listen EACCES 0.0.0.0:80
```

This means that something is already listening on port 80. On Windows, it is common that Skype is grabbing the port (otherwise some other software).

**Comment by Jhynjhiruu** [comment] 2017-10-04 08:45
@JoelLarson 

> This means that something is already listening on port 80. On Windows, it is common that Skype is grabbing the port (otherwise some other software)
And how would I stop other software using it? Skype isn't active.

**Comment by JoelLarson** [comment] 2017-10-05 13:13
@Jhynjhiruu Skype was just an example of a common Windows software that takes over port 80. Running this command in a command prompt with Administrator rights should give you an idea of where the problem is: `netstat -anb`

**Comment by SomeoneWeird** [comment] 2017-10-07 23:22
@Jhynjhiruu mentioned he got this working in another issue. Closing.

**Closed by SomeoneWeird** 2017-10-07 23:22 UTC

**Comment by Jhynjhiruu** [comment] 2017-10-08 07:05
Actually that was likely due to me switching to Ubuntu not doing something special on Windows.
